---
title: "test"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{test}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(data.table)
library(fidelis)
library(magrittr)
library(knitr)
library(kableExtra)
library(formattable)
library(ggplot2)
```

```{r}

products <- LETTERS[1:5]
providers <- paste0('Provider', 1:4)
months <- seq.Date(as.Date('2017-01-01'), as.Date('2018-12-01'), by = 'month')

D <- expand.grid(products = products,
                 providers = providers,
                 effper = months) %>%
  as.data.table() %>%
  .[, `:=`(value = sample(1000:2000, nrow(.), replace = T),
           util = sample(100:200, nrow(.), replace = T),
           mm = sample(50:100, nrow(.), replace = T))]

D_agg <- aggregate_all(D,
                       group_vars = c('products', 'providers', 'effper'),
                       agg_vars = c('value', 'util', 'mm'),
                       no_all = 'effper')

D_agg <- D_agg[order(products != 'ALL', products, providers != 'ALL', providers, effper)]

D_agg[,`:=`(cost_pmpm = value/mm,
        claims_per_mm = util/mm*12,
        cost_per_claim = value/util,
        effper = as.Date(effper))]

D3 <- merge(D_agg,
            set_dates(as.Date('2018-12-01'))[!is.na(col), .(effper, col)],
            by = 'effper')


```
